alias els="eza -bG --git --icons --group-directories-first"
alias elh="eza -lbGF --git --icons --group-directories-first"
alias ell="eza -lbF --git --icons --group-directories-first"
alias elt="eza -lbF --git --icons --group-directories-first --tree --level=2"
alias ela="eza -lbhHgSa@ --git --color-scale --group-directories-first --icons"
